### ISSUE TITLE
Tematyka następnych cykli

### ISSUE THREAD

**Issue by qofnaught** [WykopWyzwanie/wykop_wyzwaniepython#16]
- [x] pytanie o propozycje
- [x] głosowanie
- [x] podsumowanie (wybranie kilku następnych tematów?)

**Comment by qofnaught** [comment]
[Wpis ze zbieraniem propozycji](http://www.wykop.pl/wpis/18895795/)

**Comment by qofnaught** [comment]
[Wpis z głosowaniem](http://www.wykop.pl/wpis/18942155)

**Comment by jmolinski** [comment]
Tematy kilku następnych cykli są wybrane - więcej w readme.

---

https://github.com/WykopWyzwanie/wykop_wyzwaniepython/blob/master/README.md
