### ISSUE TITLE
Testowanie rozwiązania

### ISSUE THREAD

**Issue by Jonarzz** [WykopWyzwanie/wykop_wyzwaniepython#2]
Czy jest jakiś sposób, żeby przetestować napisany skrypt (rozwiązanie) na podstawie plików z archiwum testowego?

**Comment by qofnaught** [comment]
Aktualnie nie, najprawdopodobniej dzisiaj wrzucimy skrypt testujący (przynajmniej te daty).

**Comment by qofnaught** [comment]
Zrobiony, w repozytorium o nazwie **test_rozwiazania.py**.
