### ISSUE TITLE
Przykładowe rozwiązanie - wersja łatwa

### ISSUE THREAD

**Issue by qofnaught** [WykopWyzwanie/wykop_wyzwaniepython#8]

**Comment by jmolinski** [comment]
- [x] listing
- [x] omówienie rozwiązania

**Comment by jmolinski** [comment]
Zrobię to do max. 25/08/2016.

**Comment by jmolinski** [comment]
https://github.com/WykopWyzwanie/wykop_wyzwaniepython/commit/e1abd611e5a2c38b653ab4511dabea89986184f9

**Comment by jmolinski** [comment]
https://github.com/WykopWyzwanie/wykop_wyzwaniepython/wiki/Zadanie-1.1-om%C3%B3wienie-rozwi%C4%85zania
